server:
  port: 8080
spring:
  datasource:
    username: root
    password: ths19971126
    url: jdbc:mysql://192.168.128.128:3306/one?useUnicode=true&characterEncoding=UTF-8

  redis:
    database: 0
    host: 192.168.128.128
    port: 6379
    password: '000'



mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.hongsheng.one.entity
  configuration:
    map-underscore-to-camel-case: true
